function func1() {
    const a=document.querySelector(".heading")
    const b=document.querySelector(".loading")
    a.style.display="none"
    b.style.display="block"
}
function func2() {
    const a=document.querySelector(".all")
    a.style.backgroundColor="black"
    a.style.color="white"
    const b=document.querySelector(".compass")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
    f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func3() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="black"
    a.style.color="white"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
    f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func33() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="black"
    c.style.color="white"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
    f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func4() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="black"
    d.style.color="white"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
    f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func5() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
   e.style.backgroundColor="black"
    e.style.color="white"
    const f=document.querySelector(".polimer")
    f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func6() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="black"
    f.style.color="white"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func7() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="black"
    g.style.color="white"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func8() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="black"
    h.style.color="white"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func9() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="black"
    j.style.color="white"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}

function func10() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="black"
    k.style.color="white"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func11() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="black"
    l.style.color="white"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"

}
function func12() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="black"
    m.style.color="white"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}

function func13() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="black"
    n.style.color="white"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}

function func14() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="black"
    o.style.color="white"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}

function func15() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="black"
    p.style.color="white"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}

function func16() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="black"
    q.style.color="white"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}

function func17() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="black"
    r.style.color="white"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}

function func18() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="black"
    s.style.color="white"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="beige"
    t.style.color="black"
}
function func19() {
    const a=document.querySelector(".compass")
    a.style.backgroundColor="beige"
    a.style.color="black"
    const b=document.querySelector(".all")
    b.style.backgroundColor="beige"
    b.style.color="black"
    const c=document.querySelector(".New")
    c.style.backgroundColor="beige"
    c.style.color="black"
    const d=document.querySelector(".News")
    d.style.backgroundColor="beige"
    d.style.color="black"
    const e=document.querySelector(".ecma")
    e.style.backgroundColor="beige"
    e.style.color="black"
    const f=document.querySelector(".polimer")
f.style.backgroundColor="beige"
    f.style.color="black"
    const g=document.querySelector(".cartoons")
    g.style.backgroundColor="beige"
    g.style.color="black"
    const h=document.querySelector(".extra-1")
    h.style.backgroundColor="beige"
    h.style.color="black"
    const j=document.querySelector(".extra-2")
    j.style.backgroundColor="beige"
    j.style.color="black"
    const k=document.querySelector(".extra-3")
    k.style.backgroundColor="beige"
    k.style.color="black"
    const l=document.querySelector(".extra-4")
    l.style.backgroundColor="beige"
    l.style.color="black"
    const m=document.querySelector(".extra-5")
    m.style.backgroundColor="beige"
    m.style.color="black"
    const n=document.querySelector(".extra-6")
    n.style.backgroundColor="beige"
    n.style.color="black"
    const o=document.querySelector(".extra-7")
    o.style.backgroundColor="beige"
    o.style.color="black"
    const p=document.querySelector(".extra-8")
    p.style.backgroundColor="beige"
    p.style.color="black"
    const q=document.querySelector(".extra-9")
     q.style.backgroundColor="beige"
    q.style.color="black"
    const r=document.querySelector(".extra-10")
    r.style.backgroundColor="beige"
    r.style.color="black"
    const s=document.querySelector(".extra-11")
     s.style.backgroundColor="beige"
    s.style.color="black"
    const t=document.querySelector(".extra-12")
    t.style.backgroundColor="black"
    t.style.color="white"
}
function acc() {
    const a=document.querySelector(".border")
    const b=document.querySelector(".icons")
    b.style.color="black"
    b.style.backgroundColor="white"
    a.style.border="2px solid black"
}
function  short() {
    const a=document.querySelector(".shorts")
    const b=document.querySelector(".icons")
    b.style.color="white"
    b.style.backgroundColor="black"
}
function home() {
    const b=document.querySelector(".icons")
    b.style.color="black"
    b.style.backgroundColor="white"
}
function search() {
    const a=document.querySelector(".headering")
    const b=document.querySelector(".two")
    const c=document.querySelector(".mainbar")
    a.style.display="none"
    b.style.display="none"
    c.style.display="block"
}
function searching() {
    const a=document.querySelector(".headering")
    const b=document.querySelector(".two")
    const c=document.querySelector(".mainbar")
    a.style.display="block"
    b.style.display="block"
    c.style.display="none"
}
function connect() {
    const a=document.querySelector(".headering")
    const b=document.querySelector(".two")
    const c=document.querySelector(".connector")
    const d=document.querySelector(".icons")
    const e=document.querySelector(".three")
    a.style.opacity="40%"
    b.style.opacity="40%"
    d.style.opacity="40%"
    e.style.opacity="40%"
    c.style.display="block"
}
function cancel() {
    const a=document.querySelector(".headering")
    const b=document.querySelector(".two")
    const c=document.querySelector(".connector")
    const d=document.querySelector(".icons")
    const e=document.querySelector(".three")
    a.style.opacity="100%"
    b.style.opacity="100%"
    d.style.opacity="100%"
    e.style.opacity="100%"
    c.style.display="none"
}
function notification() {
    const a=document.querySelector(".headering")
    const b=document.querySelector(".two")
    const c=document.querySelector(".three")
    a.style.display="none"
    b.style.display="none"
    c.style.display="block"
}
function clo() {
    const a=document.querySelector(".headering")
    const b=document.querySelector(".two")
    const c=document.querySelector(".three")
    a.style.display="block"
    b.style.display="block"
    c.style.display="none"
}


